# Generated by Django 3.1.2 on 2021-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIN', '0002_auto_20210620_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cBirthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
