# Generated by Django 3.1.2 on 2021-06-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIN', '0004_auto_20210620_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cBirthday',
        ),
    ]
