# Generated by Django 3.1.2 on 2021-06-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WIN', '0005_remove_student_cbirthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cEmail',
        ),
    ]
